name: Quality Check Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Lint
        run: npm run lint

      - name: Run TypeScript type-check
        run: npm run type-check

      - name: Run emu and get BASE_URL
        run: |
          npm run emu 2>&1 | tee emu_output.log &
          # Get the URL of the hosting emulator
          while true; do
              # Use grep to find the URL and sed to extract it properly
              HOSTING_URL=$(grep -o "Local server: http://[0-9.]\+:[0-9]\+" emu_output.log | sed 's/Local server: //')
              if [ -n "$HOSTING_URL" ]; then
                  echo "Hosting URL detected: $HOSTING_URL"
                  echo "BASE_URL=$HOSTING_URL" >> $GITHUB_ENV
                  break
              fi
              sleep 1
          done

      - name: Wait for dev server to start
        run: npx wait-on ${{env.BASE_URL}}

      - name: Run Tests
        run: npm test
        env:
          BASE_URL: ${{env.BASE_URL}}
